### ISSUE TITLE
Add redshift / sct functionality (as a separate indicator, possibly?)

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-indicator-display#14]
@tari01 @mariogrip @flexiondotorg 

I have looked into screen color temperature stuff today, setting a lower value than 6500K on a screen regarding its color temperature is really helpful for people with macula degeneration (also prophylactically, btw).

Thus, I would like to provide a system indicator that allows the user to be in charge of the screen's color temperature. I know that there is redshift-gtk (and AppIndicator), but the AppIndicator menu is pretty minimal and it is mainly meant to be a frontend for the redshift cmdline tool. The redshift tool sets the screen color temperature dynamically based on day time / time zone. This is unsufficient for the use case, I have in mind, for two reasons:

(1) Users shall be able to set a static screen color temperature value (via a slider or such)

(2) Users shall be able to set a base line value for sct and add the redshift utility on top (thus, the screen becoming more read at night and less red during daytime).

Btw. my current solution is a "sct 4500" call via a XDG autostart .desktop file. However, it might be nice to have a versatile system indicator at hand that allows configuration of the screen color temperature.

I think the best place for placing such an indicator is this project (ayatana-indicator-display). Would this be in line with what devs at UBports require from the display indicator? Does Ubuntu Touch have redshifting support at all, already? Does Mir support it as a backend?

Request for comments and feedback.

**Comment by tari01** [comment]
Just a quick thought from me (a hardcore redshift-gtk user). I would like to avoid creating a new indicator at all costs. I'm OK with giving the display indicator redshift functionality. Should it be decided that it is not the right place, perhaps we would be better off collaborating with the redshift-gtk people, and try to augment their indicator (if they are interested, of course).

**Comment by flexiondotorg** [comment]
I like this idea. I have been using Redshift for a long while but it is not seeing active upstream development and the interaction with geoclue is the causes for some issues in Debian/Ubuntu. The Geoclue agent is Python, which is not great battery endurance on laptops.

  * Setting a static screen temp is fine, but any slider to configure that should have some labelled makers to help guide users to some suggested shift settings.
  * I don't think `sct` is fit for purpose since it doesn't support multiple displays AFAICT. I'd recommend [`xsct`](https://github.com/faf0/sct) which does support multiple displays, looks to implement something like the redshift tables and has recent development activity.
    * `xsct` would need uploading to Debian/Ubuntu.

However `sct` and `xsct` use xrandr, so I don't think either will be suitable for UBports and Mir.

**Comment by sunweaver** [comment]
Hi,

> I like this idea. I have been using Redshift for a long while but it is not seeing active upstream development and the interaction with geoclue is the cause for some issues in Debian/Ubuntu. The Geoclue agent is Python, which is not great for battery endurance on laptops. I am trying to reduce/irradicate the number of long-running Python applications in Ubuntu MATE to help prolong battery endurance.

Nice!

> * Setting a static screen temp is fine, but any slider to configure that should have some labelled makers to help guide users to some suggested shift settings.

This depends on the IDO widgets we have at hand. I don't know them all by heart. Will see.

> * I don't think `sct` is fit for purpose since it doesn't support multiple displays AFAICT. I'd recommend [`xsct`](https://github.com/faf0/sct) which does support multiple displays, looks to implement something like the redshift tables and has recent development activity.
>   
>   * `xsct` would need uploading to Debian/Ubuntu.
> 
> However `sct` and `xsct` use xrandr, so I don't think either will be suitable for UBports and Mir.

This has been addressed now. The sct tool will be phased out ...
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=984779#20

... while xsct has just been uploaded to NEW:
https://ftp-master.debian.org/new/xsct_1.6-1.html

**Comment by sunweaver** [comment]
@flexiondotorg @tari01: xsct is now in Debian testing [1].

@tari01: adding redshift support (for desktops at first) should be on our midterm road map. (As paid work).

[1] https://tracker.debian.org/pkg/xsct

**Comment by sunweaver** [comment]
as redshift support for the display indicator is not a low hanging fruit, please work on other work items first...
