### ISSUE TITLE
Rename org.ayatana.display.gschema.xml.in to org.ayatana.indicator.display.gschema.xml.in.

### ISSUE THREAD

**Issue by Ionic** [AyatanaIndicators/ayatana-indicator-display#55]
Currently, this indicator installs its gsettings schema as `${prefix}/share/glib-2.0/schemas/org.ayatana.display.gschema.xml`, but all the other indicators use the `org.ayatana.indicator.foo` file name scheme.

It should follow this convention for consistency.

**Comment by Ionic** [comment]
Also, it installs a file called `org.ayatana.indicator.rotation_lock` into `${prefix}/share/ayatana/indicators` - shouldn't that be `org.ayatana.indicator.display` for consistency?

**Comment by sunweaver** [comment]
Resolved via b3a400f6db9a97b982915af2a9b4a3aacdf72c29. Thanks for reporting.

**Comment by Ionic** [comment]
Do you intend to keep it being named `org.ayatana.indicator.rotation_lock` in the indicators dir?

https://github.com/AyatanaIndicators/ayatana-indicator-display/blob/a85903d5c42708885eef91adf1b792e9a94cb88f/data/CMakeLists.txt#L54-L58
