### ISSUE TITLE
Hide redshifting/brightness slider, if not support by Xserver / driver

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-indicator-display#70]
I just tested the new redshift feature of the display indicator in X2Go's nxagent. Nothing happens there. So we should not show the redshifting controls on nxagent.

Similar in a KVM VM (both Spice/VNC backends, graphical drivers: QXL / virtio). No redshifting happens when moving the slider.

I will log out of my local machine's session now and test MATE desktop (not my daily driver) to see if it works there.

**Comment by sunweaver** [comment]
Redshifting does not work, when Xserver runs in a qemu/KVM instance (xrandr shows Virtual-X as output)

Redshifting does not work in X2Go session (check with RDA?)

@tari01 any opinion on this?

**Comment by tari01** [comment]
> Redshifting does not work, when Xserver runs in a qemu/KVM instance (xrandr shows Virtual-X as output)
> 
> Redshifting does not work in X2Go session (check with RDA?)
> 
> @tari01 any opinion on this?

I'm not really familiar with the internals of a virtual X, but perhaps it would be good to open an issue against `xsct`, and fall back on libRda detection as a last resort...

**Comment by tari01** [comment]
@sunweaver: I did some research into how we could detect a virtual environment. `virt-what` would be perfect, but it needs root so it's out. Using `libxrandr` with some string parsing can give us what we need. Are we okay with adding `libxrandr` as a dependency only for this?

**Comment by sunweaver** [comment]
> @sunweaver: I did some research into how we could detect a virtual environment. `virt-what` would be perfect, but it needs root so it's out. Using `libxrandr` with some string parsing can give us what we need. Are we okay with adding `libxrandr` as a dependency only for this?

Yes, sure.

**Comment by sunweaver** [comment]
xrandr on the command line provides the needed info, as well.
